### ISSUE TITLE
Swagger types map to missing Datetime object

### ISSUE THREAD

**Issue by RowdyElectron** [gellu/godaddy-api-client#1]
For example, in DomainDetail.php, the types 'expires', 'renew_deadline', and 'created_at' reference a model 'Datetime' which doesn't exist and an error occurs.

Disabling (commenting-out) these values in the $swaggerTypes array removes the error, though causes null values in the end product.

**Comment by gellu** [comment]
Fixed in: https://github.com/gellu/godaddy-api-client/pull/3
Thanks for an input.
